version: "3"

volumes:
    postgres:

services:
  db:
    image: postgres:10
    expose:
      - "5444"
    ports:
      - 5444:5432
    volumes:
      - /root/pg:/var/lib/postgresql/data
      - ./postgres/initDB.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=musicexpress
      - POSTGRES_PASSWORD=postgres

  main_service:
    image: kudesnjk/musicexpress_deploy:latest
    ports:
      - 8085:8085
    command: ./main_service config.json
    volumes:
      - /root/2020_2_CodeExpress/album_posters:/project/album_posters
      - /root/2020_2_CodeExpress/artist_avatars:/project/artist_avatars
      - /root/2020_2_CodeExpress/artist_posters:/project/artist_posters
      - /root/2020_2_CodeExpress/playlist_posters:/project/playlist_posters
      - /root/2020_2_CodeExpress/track_audio:/project/track_audio
      - /root/2020_2_CodeExpress/avatars:/project/avatars
    links:
      - session_service
      - track_service
    depends_on:
      - session_service
      - track_service
      - db

  session_service:
    image: kudesnjk/musicexpress_deploy:latest
    ports:
      - 8086:8086
    command: ./session_service config.json
    links:
      - db
    depends_on:
      - db

  track_service:
    image: kudesnjk/musicexpress_deploy:latest
    ports:
      - 8087:8087
    command: ./track_service config.json
    links:
      - db
    depends_on:
      - db
